# Generated by Django 4.2.6 on 2023-10-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_alter_applicantdetails_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='email_id',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='address_line_1',
            field=models.CharField(max_length=200),
        ),
    ]
