# Generated by Django 4.2.6 on 2023-10-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0004_alter_applicantdetails_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='address_line_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='months',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='years',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='zip_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
